apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy: {}
  template:
    metadata: 
      labels:
        app: user-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-user-service:5432/userdb
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: IMAGE_URL/user-service:latest
          name: user-service
          resources:
            limits:
              cpu: "250m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      restartPolicy: Always
status: {} 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - name: "80" 
      port: 80
      targetPort: 8080
  selector:
    app: user-service
status:
  loadBalancer: {}                  
